# Generated by Django 4.1.5 on 2023-01-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='StudentName',
            new_name='studentname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='TeacherName',
            new_name='teachername',
        ),
    ]
